name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up QEMU (for multi-arch builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3️⃣ Set up Python for running tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11



      # 8️⃣ Deploy to Azure VM over SSH
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: api_avengers
          key: ${{ secrets.AZURE_VM_KEY }}
          script: |
            cd ./asif/login_node_deploy
            docker compose down

            git pull origin main
            
            docker compose up --build -d
