name: CI Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to VM and restart stack
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: api_avengers
          key: ${{ secrets.AZURE_VM_KEY }}
          script: |
            set -e
            cd ./asif/login_node_deploy
            # Stop current stack
            docker compose down --remove-orphans || true
            # Ensure clean images before rebuild (your request)
            docker image prune -af || true
            # Pull latest repo changes
            git pull origin main
            # Rebuild and start in detached mode
            docker compose up --build -d